### ISSUE TITLE
Release to chef supermarket?

### ISSUE THREAD

**Issue by deees** [aetrion/exabgp-cookbook#4]
Any plans to publish this cookbook to https://supermarket.chef.io ? :smile:

**Comment by martinisoft** [comment]
@deees Yes, I'll be cutting a new release this week and publishing it there. Waiting to merge another patch and releasing before the LWRP rewrite.

**Comment by deees** [comment]
Awesome! :clap:

**Comment by martinisoft** [comment]
@deees It's officially [out there now](https://supermarket.chef.io/cookbooks/exabgp)

**Comment by deees** [comment]
:+1:

**Comment by rll3** [comment]
:+1:
